modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "CC0-1.0 License"

[[mods]]
modId = "salem"
version = "${version}"
displayName = "Salem"
authors = "Buuz135, Ridanisaurus"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.salem]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.salem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.salem]]
modId = "architectury"
mandatory = true
versionRange = "[2.3.23,)"
ordering = "AFTER"
side = "BOTH"